#!/usr/bin/env node
// Station coordinates for the frontend map:
//   data/processed/{stations,trains}.json + data/external/datameet-stations.json (CC0)
//   -> frontend/public/station-coords.json ({CODE: [lat, lon]}) + data/reports/geocode-report.md
//
// Usage: node geocode.ts [--processed DIR] [--external FILE] [--out FILE] [--reports DIR]
// Run after preprocess.ts. The output is committed so the frontend build needs no data step.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { edgeConsistent, fillByInterpolation, findOutliers, inIndia, type GeoStop, type LatLon } from "./lib/geocode.ts";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");

function arg(name: string, def: string): string {
  const i = process.argv.indexOf("--" + name);
  return i >= 0 && process.argv[i + 1] ? process.argv[i + 1] : def;
}

const PROCESSED = resolve(arg("processed", join(root, "data/processed")));
const EXTERNAL = resolve(arg("external", join(root, "data/external/datameet-stations.json")));
const OUT = resolve(arg("out", join(root, "frontend/public/station-coords.json")));
const REPORTS = resolve(arg("reports", join(root, "data/reports")));

const stations: { code: string; name: string; train_count: number }[] = JSON.parse(readFileSync(join(PROCESSED, "stations.json"), "utf8"));
const trains: { number: string; stops: { code: string; distance_km: number }[] }[] = JSON.parse(readFileSync(join(PROCESSED, "trains.json"), "utf8"));
const external: { features: { geometry: { coordinates: [number, number] } | null; properties: { code?: string } }[] } = JSON.parse(
  readFileSync(EXTERNAL, "utf8"),
);

// Stations renamed or recoded since the datameet snapshot, mapped to the datameet code of the same
// (or an adjacent, within a few km) station. Checked by hand; the outlier guard still validates them.
const ALIASES: Record<string, string> = {
  CSMT: "CSTM", // Mumbai CSMT, formerly CST
  MMCT: "BCT", // Mumbai Central
  NRLN: "NRL", // Neral narrow-gauge platform
  PRNC: "PRNA", // Purnia Court, next to Purnia Jn
  PYGS: "PRG", // Prayagraj Sangam, next to Prayag
  YNRK: "RKSH", // Yog Nagari Rishikesh
  SGTY: "SEL", // Sankrail Goods Terminal, at Sankrail
};

const wanted = new Set(stations.map((s) => s.code));
const routes: GeoStop[][] = trains.map((t) => t.stops.map((s) => ({ code: s.code, distance_km: s.distance_km })));

const coords = new Map<string, LatLon>();
let outOfBounds = 0;
for (const f of external.features) {
  const code = f.properties.code?.trim().toUpperCase();
  if (!code || !f.geometry || !wanted.has(code) || coords.has(code)) continue;
  const [lon, lat] = f.geometry.coordinates;
  const p: LatLon = [lat, lon];
  if (!inIndia(p)) {
    outOfBounds++;
    continue;
  }
  coords.set(code, p);
}
const byCode = new Map(external.features.filter((f) => f.geometry && f.properties.code).map((f) => [f.properties.code!.trim().toUpperCase(), f.geometry!.coordinates]));
let aliased = 0;
for (const [code, target] of Object.entries(ALIASES)) {
  const c = byCode.get(target);
  if (!wanted.has(code) || coords.has(code) || !c) continue;
  coords.set(code, [c[1], c[0]]);
  aliased++;
}
const matched = coords.size;

const outliers = findOutliers(coords, routes);
for (const c of outliers) coords.delete(c);

const filled = fillByInterpolation(coords, routes, wanted);
const unresolved = [...wanted].filter((c) => !coords.has(c)).sort();

// Adjacent stops that still disagree with the timetable distance: mostly codes the raw data reuses
// for two different stations (BPR, MGR; see the quality report), which no coordinate can satisfy.
const inconsistent: string[] = [];
let edges = 0;
for (const [t, stops] of trains.entries()) {
  for (let i = 1; i < stops.stops.length; i++) {
    const a = stops.stops[i - 1];
    const b = stops.stops[i];
    const pa = coords.get(a.code);
    const pb = coords.get(b.code);
    if (!pa || !pb) continue;
    edges++;
    if (!edgeConsistent(pa, pb, b.distance_km - a.distance_km)) inconsistent.push(`- ${trains[t].number} ${a.code} -> ${b.code}`);
  }
}

const out: Record<string, LatLon> = {};
for (const code of [...coords.keys()].sort()) {
  const [lat, lon] = coords.get(code)!;
  out[code] = [Math.round(lat * 1e4) / 1e4, Math.round(lon * 1e4) / 1e4];
}
mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, JSON.stringify(out));

const pct = (n: number) => `${((100 * n) / wanted.size).toFixed(1)}%`;
const byName = new Map(stations.map((s) => [s.code, s]));
const list = (codes: Iterable<string>) => [...codes].sort().map((c) => `- ${c}: ${byName.get(c)?.name ?? "?"} (${byName.get(c)?.train_count ?? 0} trains)`).join("\n");
const report = `# Geocoding report

Generated by \`scripts/geocode.ts\` from the datameet/railways station list (CC0).

| | Stations | Share |
|---|---:|---:|
| In the timetable | ${wanted.size} | 100% |
| Matched by code in datameet (including ${aliased} renamed codes) | ${matched} | ${pct(matched)} |
| Rejected: outside India bounds | ${outOfBounds} | |
| Rejected: inconsistent with timetable distances | ${outliers.size} | |
| Filled by interpolation along train routes | ${filled.size} | ${pct(filled.size)} |
| **Resolved (written)** | **${coords.size}** | **${pct(coords.size)}** |
| Unresolved (map draws straight past them) | ${unresolved.length} | ${pct(unresolved.length)} |

## Rejected as inconsistent (then re-filled by interpolation where possible)

${list(outliers) || "None."}

## Adjacent stops still inconsistent with rail distance (${inconsistent.length} of ${edges})

${inconsistent.join("\n") || "None."}

## Unresolved

${list(unresolved) || "None."}
`;
mkdirSync(REPORTS, { recursive: true });
writeFileSync(join(REPORTS, "geocode-report.md"), report);

console.log(
  `geocode: ${wanted.size} stations, matched ${matched}, outliers ${outliers.size}, interpolated ${filled.size}, ` +
    `resolved ${coords.size} (${pct(coords.size)}), unresolved ${unresolved.length} -> ${OUT}`,
);
