// Station coordinates for the map. They are a static file generated by scripts/geocode.ts and served
// from /public, fetched once per page load, so drawing a route never waits on the API.
import type { Journey, Segment } from "./types";

export type LatLon = [number, number];
export type Coords = Record<string, LatLon>;

let coordsPromise: Promise<Coords> | null = null;

export function loadCoords(): Promise<Coords> {
  coordsPromise ??= fetch("/station-coords.json")
    .then((r) => (r.ok ? (r.json() as Promise<Coords>) : {}))
    .catch(() => {
      coordsPromise = null; // allow a retry on the next mount
      return {};
    });
  return coordsPromise;
}

/** The segment's path through every stop that has coordinates, so the line follows the real route. */
export function segmentPath(seg: Segment, coords: Coords): LatLon[] {
  const out: LatLon[] = [];
  for (const s of seg.stops) {
    const p = s.code ? coords[s.code] : undefined;
    if (p) out.push(p);
  }
  return out;
}

export function journeyPaths(j: Journey, coords: Coords): LatLon[][] {
  return j.segments.map((s) => segmentPath(s, coords));
}

export function boundsOf(points: LatLon[]): [LatLon, LatLon] | null {
  if (points.length === 0) return null;
  let [minLat, minLon] = points[0];
  let [maxLat, maxLon] = points[0];
  for (const [lat, lon] of points) {
    minLat = Math.min(minLat, lat);
    maxLat = Math.max(maxLat, lat);
    minLon = Math.min(minLon, lon);
    maxLon = Math.max(maxLon, lon);
  }
  return [
    [minLat, minLon],
    [maxLat, maxLon],
  ];
}

export const INDIA_CENTER: LatLon = [22.6, 80.5];
